services:
  - name: elasticsearch
    type: background
    runtime: docker
    repo: https://github.com/tuo-repo/elasticsearch-render
    branch: main
    plan: starter
    envVars:
      - key: ES_JAVA_OPTS
        value: "-Xms256m -Xmx256m"
      - key: PORT
        value: "9200"
      - key: discovery.type
        value: single-node
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 10
      
